import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import axios from 'axios';
import toast from 'react-hot-toast';

const API = import.meta.env.VITE_API_URL || '/api';
const PHASE_COLORS = ['#5b5ef4','#00d4e8','#a855f7','#00e87a'];

const DEFAULT_ROADMAP = {
  timeline: '12 weeks', dailyTarget: '4-5 hours', weeklyGoal: 'Complete 1 phase milestone',
  topTip: 'Consistency beats intensity. Track progress daily using PlaCIQ streak.',
  phases: [
    { week:'1-4', focus:'DSA Mastery', tasks:['LeetCode 150 problems','Trees & Graphs deep dive','DP patterns mastery','Sliding window & Binary search','System complexity analysis'], resources:['NeetCode 150','AlgoExpert','Striver SDE Sheet'], milestone:'Solve 100 LeetCode problems' },
    { week:'5-8', focus:'System Design', tasks:['HLD concepts & patterns','LLD & design principles','Design Twitter/Uber/Netflix','Mock design rounds daily','DB indexing & sharding'], resources:['Grokking System Design','ByteByteGo','System Design Primer'], milestone:'Complete 10 system designs' },
    { week:'9-11', focus:'Projects & Portfolio', tasks:['Build 2 full-stack projects','Deploy on Vercel/AWS','Write technical blogs','Optimize GitHub profile','Contribute to open source'], resources:['GitHub Stars','Dev.to','Portfolio guide'], milestone:'2 deployed projects live' },
    { week:'12', focus:'Apply & Interview', tasks:['Apply to 20+ companies','Mock interviews daily','HR round prep','Salary negotiation strategy'], resources:['Glassdoor','LinkedIn','Blind','levels.fyi'], milestone:'20+ applications sent' },
  ]
};

export default function Strategy() {
  const { user } = useAuth();
  const [roadmap, setRoadmap] = useState(DEFAULT_ROADMAP);
  const [loading, setLoading] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [completed, setCompleted] = useState(new Set());

  const generate = async () => {
    setLoading(true);
    try {
      const { data } = await axios.post(`${API}/agent/analyze`, {
        agentType: 'strategy',
        data: { skills: user?.profile?.skills || ['Python','React'], role: user?.profile?.targetRole || 'Software Engineer', companies: user?.profile?.targetCompanies || ['Google','Microsoft'], cgpa: user?.profile?.cgpa || 8.0, college: user?.profile?.college, year: user?.profile?.year }
      });
      if (data.result?.phases) setRoadmap(data.result);
      setGenerated(true);
      toast.success('Personalized roadmap generated by Claude AI! 🗺️');
    } catch (e) {
      setGenerated(true);
      toast('Using default roadmap — configure AI key for personalized results', { icon:'ℹ️' });
    } finally { setLoading(false); }
  };

  const toggleTask = (phaseIdx, taskIdx) => {
    const key = `${phaseIdx}-${taskIdx}`;
    setCompleted(s => { const n = new Set(s); n.has(key) ? n.delete(key) : n.add(key); return n; });
  };

  const totalTasks = roadmap.phases.reduce((a, p) => a + p.tasks.length, 0);
  const completedCount = completed.size;
  const progress = Math.round((completedCount / totalTasks) * 100);

  return (
    <div style={{ padding:'28px 32px', maxWidth:1100 }}>
      <div className="page-header">
        <div>
          <h1 className="page-title">Placement Strategy</h1>
          <p className="page-subtitle">AI-generated {roadmap.timeline} roadmap tailored to your profile and target companies.</p>
        </div>
        <button onClick={generate} disabled={loading} className="btn btn-primary">
          {loading ? <><div className="spinner" /> Generating with Claude AI...</> : generated ? '🔄 Regenerate AI Roadmap' : '✦ Generate My Roadmap'}
        </button>
      </div>

      {/* Meta cards */}
      <div style={{ display:'grid', gridTemplateColumns:'repeat(4,1fr)', gap:14, marginBottom:24 }}>
        {[
          { icon:'⏱', label:'Timeline', value:roadmap.timeline, color:'var(--accent)' },
          { icon:'📅', label:'Daily Target', value:roadmap.dailyTarget, color:'var(--cyan)' },
          { icon:'✅', label:'Progress', value:`${completedCount}/${totalTasks} tasks`, color:'var(--green)' },
          { icon:'🎯', label:'Completion', value:`${progress}%`, color:'var(--amber)' },
        ].map((m,i) => (
          <div key={i} className="card" style={{ textAlign:'center', padding:'18px 14px' }}>
            <div style={{ fontSize:24, marginBottom:6 }}>{m.icon}</div>
            <div style={{ fontFamily:'Outfit', fontSize:18, fontWeight:700, color:m.color, marginBottom:3 }}>{m.value}</div>
            <div style={{ fontSize:12, color:'var(--text3)' }}>{m.label}</div>
          </div>
        ))}
      </div>

      {/* Overall progress bar */}
      <div className="card" style={{ marginBottom:24, padding:'18px 24px' }}>
        <div style={{ display:'flex', justifyContent:'space-between', marginBottom:10 }}>
          <span style={{ fontSize:13, fontWeight:600 }}>Overall Roadmap Progress</span>
          <span style={{ fontSize:13, fontFamily:'JetBrains Mono', color:'var(--accent2)' }}>{progress}%</span>
        </div>
        <div className="progress-bar" style={{ height:8 }}>
          <div className="progress-fill" style={{ width:`${progress}%`, background:'var(--gradient)', height:'100%' }} />
        </div>
      </div>

      {/* Top tip */}
      {roadmap.topTip && (
        <div style={{ marginBottom:24, padding:'14px 20px', background:'var(--accent-dim)', border:'1px solid var(--accent)30', borderRadius:14, display:'flex', gap:12, alignItems:'flex-start' }}>
          <span style={{ fontSize:18, flexShrink:0 }}>✦</span>
          <div>
            <span style={{ fontSize:12, color:'var(--accent2)', fontWeight:600, textTransform:'uppercase', letterSpacing:'0.06em' }}>AI Power Tip · </span>
            <span style={{ fontSize:14, color:'var(--text2)' }}>{roadmap.topTip}</span>
          </div>
        </div>
      )}

      {/* Phases */}
      <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fit, minmax(280px, 1fr))', gap:18 }}>
        {roadmap.phases.map((phase, pi) => {
          const phaseCompleted = phase.tasks.filter((_, ti) => completed.has(`${pi}-${ti}`)).length;
          const phaseProgress = Math.round((phaseCompleted / phase.tasks.length) * 100);
          const color = PHASE_COLORS[pi % PHASE_COLORS.length];
          return (
            <div key={pi} style={{ background:'var(--surface)', border:`1px solid ${color}20`, borderRadius:18, overflow:'hidden', transition:'border-color 0.2s' }}
              onMouseEnter={e => e.currentTarget.style.borderColor=`${color}40`}
              onMouseLeave={e => e.currentTarget.style.borderColor=`${color}20`}>
              {/* Phase header */}
              <div style={{ padding:'18px 20px', background:`${color}10`, borderBottom:`1px solid ${color}20` }}>
                <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:10 }}>
                  <div>
                    <div style={{ fontSize:11, color, fontWeight:600, textTransform:'uppercase', letterSpacing:'0.06em', marginBottom:4 }}>Week {phase.week}</div>
                    <div style={{ fontFamily:'Outfit', fontSize:16, fontWeight:700 }}>{phase.focus}</div>
                  </div>
                  <div style={{ textAlign:'right' }}>
                    <div style={{ fontSize:18, fontWeight:800, fontFamily:'Outfit', color }}>{phaseProgress}%</div>
                    <div style={{ fontSize:10, color:'var(--text3)' }}>complete</div>
                  </div>
                </div>
                <div className="progress-bar" style={{ height:5 }}>
                  <div style={{ height:'100%', background:color, borderRadius:2, width:`${phaseProgress}%`, transition:'width 0.5s ease' }} />
                </div>
              </div>

              {/* Tasks */}
              <div style={{ padding:'14px 20px' }}>
                <div style={{ fontSize:11, color:'var(--text3)', fontWeight:600, textTransform:'uppercase', letterSpacing:'0.06em', marginBottom:10 }}>Tasks</div>
                {phase.tasks.map((task, ti) => {
                  const done = completed.has(`${pi}-${ti}`);
                  return (
                    <div key={ti} onClick={() => toggleTask(pi, ti)}
                      style={{ display:'flex', alignItems:'flex-start', gap:10, padding:'8px 0', cursor:'pointer', borderBottom:'1px solid var(--border)', transition:'all 0.15s' }}
                      onMouseEnter={e => e.currentTarget.style.paddingLeft='4px'}
                      onMouseLeave={e => e.currentTarget.style.paddingLeft='0px'}>
                      <div style={{ width:18, height:18, borderRadius:5, border:`2px solid ${done ? color : 'var(--border2)'}`, background: done ? color : 'transparent', display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0, marginTop:1, transition:'all 0.2s' }}>
                        {done && <span style={{ color:'#fff', fontSize:11, lineHeight:1 }}>✓</span>}
                      </div>
                      <span style={{ fontSize:13, color: done ? 'var(--text3)' : 'var(--text2)', textDecoration: done ? 'line-through' : 'none', lineHeight:1.5 }}>{task}</span>
                    </div>
                  );
                })}
              </div>

              {/* Resources */}
              {phase.resources?.length > 0 && (
                <div style={{ padding:'12px 20px 16px', borderTop:'1px solid var(--border)' }}>
                  <div style={{ fontSize:11, color:'var(--text3)', fontWeight:600, textTransform:'uppercase', letterSpacing:'0.06em', marginBottom:8 }}>Resources</div>
                  <div style={{ display:'flex', flexWrap:'wrap', gap:6 }}>
                    {phase.resources.map((r, i) => (
                      <span key={i} style={{ padding:'4px 10px', background:`${color}12`, border:`1px solid ${color}25`, borderRadius:20, fontSize:11, color, fontWeight:500 }}>{r}</span>
                    ))}
                  </div>
                </div>
              )}

              {/* Milestone */}
              {phase.milestone && (
                <div style={{ padding:'10px 20px', background:'var(--bg2)', borderTop:'1px solid var(--border)' }}>
                  <span style={{ fontSize:11, color:'var(--text3)' }}>🏁 Milestone: </span>
                  <span style={{ fontSize:12, color:'var(--text2)', fontWeight:500 }}>{phase.milestone}</span>
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Warning areas */}
      {roadmap.warningAreas?.length > 0 && (
        <div style={{ marginTop:20, padding:'16px 20px', background:'var(--red-dim)', border:'1px solid rgba(255,69,97,0.25)', borderRadius:14 }}>
          <div style={{ fontSize:12, color:'var(--red)', fontWeight:600, marginBottom:8 }}>⚠️ Areas Needing Attention</div>
          {roadmap.warningAreas.map((w,i) => <div key={i} className="result-item" style={{ color:'var(--text2)' }}>{w}</div>)}
        </div>
      )}
    </div>
  );
}
